Completed   Lesson 9 Level 2 Task 9
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1068
Opened 2021-06-27 19:11 UTC by arturwrls

2021-06-28 12:36 UTC, daniilsjb requested changes

2021-06-28 12:36 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_9/level_2/task_9/PrivateConstructor.java
> +}
Дело вовсе не в абстрактности. Присмотритесь к имени класса: _приватный конструктор_. Прям-таки намёк какой-то 👀

2021-06-28 19:25 UTC, daniilsjb approved these changes

2021-06-28 19:25 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_9/level_2/task_9/PrivateConstructor.java
> +abstract class PrivateConstructor {
Ключевое слово `abstract` всё равно лишнее, но да ладно с ним.

2021-06-28 19:25 UTC, merged

2021-06-29 06:47 UTC, arturwrls commented on src/main/java/students/arturs_arutjunovs/lesson_9/level_2/task_9/PrivateConstructor.java
> +abstract class PrivateConstructor {
😁 Самое интересное что я убрал слово abstract у себя в черновике где выполняю задания, надо было скопипастить мне оттуда, а ннет, решил переписать вручную😂