Lesson 10 - Level 5 - Task 13
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1141
Opened 2021-07-01 16:30 UTC by Ernests1992

2021-07-02 10:20 UTC, daniilsjb requested changes
Есть ошибка в логике и пара возможных упрощений. Думаю, что стоит сразу эти же недочёты исправить и в следующих заданиях 😅 Я посмотрел на ваши следующие PR, все остальные задания решены верно, стоит только исправить метод `addBook` (по большей мере копи-паста).

2021-07-02 10:20 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImplTest.java
> +                    "Added book title test");
Как вариант, можно выделить книгу в отдельную переменную, типа `Book book = bookReader.electronicLibrary[1];`. Тогда проверки станут немного короче.

2021-07-02 12:27 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImpl.java
> +    public boolean isDuplicate(Book newBook) {
Исправил.

2021-07-02 12:34 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImpl.java
> +    Book[] electronicLibrary = new Book[1];
Исправил.

2021-07-02 12:38 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImpl.java
> +    }
Исправил.

2021-07-02 12:58 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImplTest.java
> +    }
Добавил.

2021-07-02 13:02 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_10/level_5/task_13/BookReaderImplTest.java
> +                    "Added book title test");
Исправил.

2021-07-02 14:37 UTC, Ernests1992 commented
Исправил и дополнил задания 13.-24.

2021-07-03 19:20 UTC, daniilsjb approved these changes
👍

2021-07-03 19:20 UTC, merged