Lesson 10 Task-3 - LEVEL1
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1204
Opened 2021-07-06 11:04 UTC by DeTELo

St dmitrijs matrenicevs lesson 10 level 1 task 3

2021-07-06 19:18 UTC, daniilsjb requested changes
Стоит учиться придумывать сигнатуры методов. Это даже не связано напрямую с самим интерфейсом - дизайн кода является отдельным искусством. Поскольку задание сложное и креативное, то недочёты допускаются, но обратите внимание хотя бы на пару вещей, которые я указал. В будущем будет проще 😄

2021-07-06 19:18 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_1/task_3/SimpleList.java
> +    void deleteObject(int a, T value);
Параметр `value` мне здесь кажется лишним, и возможно первый стоит переименовать в `position` или `i` (по конвенции). С точки зрения дизайна этот метод ещё мог бы возвращать `boolean`, указывающий на то, был ли элемент убран, или даже вернуть сам убранный элемент.

2021-07-06 19:18 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_1/task_3/SimpleList.java
> +    //создать список
У этого метода странная сигнатура. Что он делает со значением `value`? Это единственный элемент списка? Почему можно передать только один элемент, а не несколько? И не стоит ли задачу создания списков оставить для конструкторов и статичных методов? 🤔

2021-07-06 19:18 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_1/task_3/SimpleList.java
> +    //найти максимальный элемент
Эти два метода возвращают `int`, но при этом тип списка нам неизвестен - он может хранить строки или какие-то кастомные объекты. Поэтому ему стоит возвращать значение типа `T`.

На самом деле правильно составить сигнатуру для этих методов сложно, поскольку нужна гарантия, что тип `T` можно сравнивать. На лекциях пока не было (вроде) затронуто необходимого для этого механизма. Но если любопытно, то это бы выглядело так:

```java
interface SimpleList<T extends Comparable<T>>
```

Но я не рекомендую пока так делать, поскольку это ограничивает возможности использования этого интерфейса.

И кстати, почему эти два метода вообще принимают параметры? 🤔

2021-07-06 19:18 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_1/task_3/SimpleList.java
> +    void removeElementBeginning(int a);
Мне кажется, что это лишний параметр.

2021-07-11 09:28 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_1/task_3/SimpleList.java
> +    void removeElementBeginning(int a);
Постарался исправить, надеюсь правильно )

2021-07-11 11:41 UTC, daniilsjb approved these changes
👍

2021-07-11 11:41 UTC, merged