St dmitrijs matrenicevs lesson 10 level 2 task 4 5
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1206
Opened 2021-07-06 11:42 UTC by DeTELo

St dmitrijs matrenicevs lesson 10 level 2 task 4-5

2021-07-06 19:25 UTC, daniilsjb requested changes

2021-07-06 19:25 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_2/task_4_5/StringDayOfTheWeekDetector.java
> +        if (number <= 7 && number != 0) {
Тут закрался хитрый баг: ничего не запрещает числу `number` быть отрицательным 🤔 Так что стоит заменить проверку на `number >= 0 && number <= 7`. Даже красивее получается.

2021-07-11 09:17 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_2/task_4_5/StringDayOfTheWeekDetector.java
> +        if (number <= 7 && number != 0) {
Исправил :)

2021-07-11 11:40 UTC, daniilsjb approved these changes
😅

2021-07-11 11:40 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_10/level_2/task_4_5/StringDayOfTheWeekDetector.java
> +        if (number >= 0 && number <= 7) {
Так, я сам ошибся. Нужно было проверять `number >= 1`, извините 🤣

2021-07-11 11:40 UTC, merged