Lesson 11 - Level 2 - Task 11
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1251
Opened 2021-07-14 14:57 UTC by Ernests1992

2021-07-14 19:27 UTC, daniilsjb requested changes
В текущей реализации идентификаторов есть немного неочевидная проблема, которую нужно исправить. Также, можете попробовать сразу использовать суффикс `L` при работе с числами типа `long`.

2021-07-14 19:27 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_11/InMemoryBookRepository.java
> +        Long newBookId = (long) (bookDataBase.size() + 1);
Прошу прощения, я не сразу обратил внимание на одну проблему. Использовать текущий размер списка в качестве идентификатора не стоит, поскольку при удалении элементов размер списка будет уменьшен и, следовательно, несколько книг могут получить один и тот же идентификатор. Стоит создать отдельную приватную переменную `Long id` и просто увеличивать её при каждом добавлении новой книги. 🙂

2021-07-15 09:14 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_11/InMemoryBookRepository.java
> +        Long newBookId = (long) (bookDataBase.size() + 1);
Исправил.

2021-07-15 09:29 UTC, daniilsjb approved these changes
👍

2021-07-15 09:29 UTC, merged