Lesson 11 Task-1-2 - LEVEL1
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1257
Opened 2021-07-14 19:52 UTC by DeTELo

Lesson 11 Task-1-2 - LEVEL1

2021-07-15 20:14 UTC, daniilsjb requested changes

2021-07-15 20:14 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_1/task_2/Task2.java
> +        System.out.println(strings);
Нет демонстрации или объяснения хранения примитивных данных.  `String` - это уже класс. Примитивными являются типы вроде `int`, `double`, `boolean` и т.д.

_Подсказка: у примитивных типов существуют специальные классы обёртки, и это связано с коллекциями 🤔_

2021-07-15 21:33 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_1/task_2/Task2.java
> +        System.out.println(strings);
У меня что-то напуталось, и я не могу сделать Push в эту ветку, можете здесь засчитать только Task1, а второй я загрузил отдельно ) Спасибо )

2021-07-16 14:44 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_1/task_2/Task2.java
> +        System.out.println(strings);
Конечно 👌

2021-07-16 14:44 UTC, daniilsjb approved these changes

2021-07-16 14:44 UTC, merged