Lesson 11 - Level 2 - Task 12
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1259
Opened 2021-07-15 09:47 UTC by Ernests1992

2021-07-15 20:23 UTC, daniilsjb requested changes

2021-07-15 20:23 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_12/InMemoryBookRepositoryTest.java
> +        assertNumericTestResult(3, bookCount, "Books counted correctly (after removal)");
Закралась ошибка. Почему после удаления элемента из базы ожидаемый размер по-прежнему 3? 🤔 Дело в том, что значение `bookCount` читается перед удалением и после не обновляется. Следовательно, тест составлен не до конца верно.

2021-07-15 20:24 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_12/InMemoryBookRepository.java
> +    Long id = 0L;
Кстати, этим свойствам стоит быть приватными. Поскольку репозитория уже поддерживает методы чтения из списка, теперь нет смысла напрямую светить этим свойством.

2021-07-16 07:55 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_12/InMemoryBookRepository.java
> +    Long id = 0L;
Исправил.

2021-07-16 07:56 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_11/level_2/task_12/InMemoryBookRepositoryTest.java
> +        assertNumericTestResult(3, bookCount, "Books counted correctly (after removal)");
Исправил.

2021-07-16 14:46 UTC, daniilsjb approved these changes
👍

2021-07-16 14:46 UTC, merged