Lesson 11 - Level 2 - Task 8
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1298
Opened 2021-07-19 20:19 UTC by dk-t

2021-07-21 13:28 UTC, daniilsjb requested changes
Я сам немного сглупил 😅

2021-07-21 15:17 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +    }
Существует специальный метод, который называется [`removeIf`](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#removeIf-java.util.function.Predicate-). Если вам интересно попробовать использовать более функциональную методику, то можете переписать этот метод таким образом:

```java
@Override
public boolean delete(Long bookId) {
    return bookList.removeIf(book -> book.getId().equals(bookId));
}
```

Цикл, конечно, наглядней 😄 Этот метод также будет удобен в некоторых будущих заданиях, можете взять на заметку.

2021-07-21 15:17 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +    }
Вы можете объединить оба теста в один: сначала можно удалить все книги, и затем убедиться, что их невозможно повторно удалить (ведь теперь их нет в репозитории):

```java
public void shouldDeleteBooksById() {
    // я использую небольшой чит с ключевым словом var 😁
    // https://www.baeldung.com/java-10-local-variable-type-inference
    var subject = new InMemoryBookRepository();
    subject.save(new Book("A1", "B1"));
    subject.save(new Book("A2", "B2"));
    subject.save(new Book("A3", "B3"));

    // Я помечаю каждую проверку номером, чтобы мы точно знали, где
    // провал в логике.
    checkTest(true, subject.delete(0L), "shouldDeleteBooksById (#0)");
    checkTest(true, subject.delete(1L), "shouldDeleteBooksById (#1)");
    checkTest(true, subject.delete(2L), "shouldDeleteBooksById (#2)");

    checkTest(false, subject.delete(0L), "shouldDeleteBooksById (#3)");
    checkTest(false, subject.delete(1L), "shouldDeleteBooksById (#4)");
    checkTest(false, subject.delete(2L), "shouldDeleteBooksById (#5)");
}
```

Таким образом мы проверили свойства самого метода: ведь это логично, что повторный вызов `delete` должен всегда возвращать `false` 🤓

К слову, было бы даже красивее сделать отдельные методы `assertTrue` и `assertFalse` вместо `checkTest(true, something>)` и прочего. Можно даже выделить их в отдельный класс, `Assertions`, и сделать их публичными и статичными методами. Тогда у вас будет разделение между тестовой логикой и тестовыми проверками:

```java
class Assertions {
    public static void assertTrue(boolean value, String testName) {
        assertCondition(value, testName, "Expected true but got false");
    }

    public static void assertFalse(boolean value, String testName) {
        assertCondition(!value, testName, "Expected false but got true");
    }

    // в будущем по аналогии можно добавить метод типа assertEqual(Object, Object) 🤔

    // универсальный метод проверки условия и репорта об ошибке теста
    private static void assertCondition(boolean condition, String testName, String message) {
        if (condition) {
            System.out.println("Test '" + testName + "' PASSED!");
        } else {
            System.out.println("Test '" + testName + "' FAILED!");
            System.out.println("  - Reason: " + message);
        }
    }
}
```

2021-07-21 17:01 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/Book.java
> +        return title.equals(book.title) && author.equals(book.author);
Вернул id.equals(book.id) && в строку 37:
return id.equals(book.id) && title.equals(book.title) && author.equals(book.author);

2021-07-21 17:01 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +        return false;
Это конечно мастер-класс) Наглядный пример как не надо писать код, вместо 7 строчек всего лишь 1.
Переписал

2021-07-21 17:02 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +        return false;
Хм.. Вот только первоначальный тест по удалению заданной книги теперь опять не проходит((

2021-07-21 17:07 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +    }
На заметку взял, task 7 также подправил.
Тесты прошли))

2021-07-21 17:12 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +    }
" Вы можете объединить оба теста в один: ..." - а вот теперь тесты прошли, магия, какая-то))

2021-07-21 17:40 UTC, dk-t commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +    }
Добавил class Assertions

2021-07-21 19:54 UTC, daniilsjb requested changes
Так, осталась ещё пара моментов, но в остальном всё супер! 🔥 В последующих заданиях тесты нужно будет писать к каждому методу.

2021-07-21 19:54 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +    }
Нужно добавить ещё один тест на удаление книг целиком. Можно назвать его `shouldDeleteBooks`, и в нём по аналогии с `shouldDeleteBooksById` добавить несколько книг, далее каждую удалить, и затем удалить повторно, убедившись, что возвращается `false`. Очень важно также дать каждой книге идентификатор, иначе ничего не произойдёт.

2021-07-21 19:54 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +        return id;
Я не сразу обратил внимание, но здесь нужно возвращать `book.getId()`, посколько на этом этапе свойство `id` уже было изменено.

2021-07-21 19:57 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepository.java
> +        return false;
Рад, что вам понравилось 😄 Я уже не помню, что было в первоначальных тестах, но вероятнее всего вы забыли выставить идентификаторы. Баги могут быть и в самих тестах, это вечная проблема тестирования.

2021-07-23 12:10 UTC, daniilsjb approved these changes
👍

2021-07-23 12:10 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +        book3.setId(2L);
Если вы позволяете методу `save` самому назначить идентификаторы, то сеттеры вызывать не нужно. Можно написать этот метод просто так:

```java
var subject = new InMemoryBookRepository();
subject.save(book1);
subject.save(book2);
subject.save(book3);

Assertions.assertTrue(subject.delete(book1), "...");
Assertions.assertTrue(subject.delete(book2), "...");
Assertions.assertTrue(subject.delete(book3), "...");

Assertions.assertFalse(subject.delete(book1), "...");
Assertions.assertFalse(subject.delete(book2), "...");
Assertions.assertFalse(subject.delete(book3), "...");
```

2021-07-23 12:10 UTC, daniilsjb commented on src/main/java/students/dmitriy_shukailo/lesson_11/level_2/task_8/InMemoryBookRepositoryTest.java
> +    Book book3 = new Book("A3", "B3");
В будущем я рекомендую писать тестовые данные в пределах каждого теста, даже если это подразумевает копи-паст. Тесты должны быть максимально изолированы друг от друга и не зависить от общих внешних данных, которые могут как-то изменяться. Также для разных тестов могут требоваться совершенно разные тестовые данные.

2021-07-23 12:10 UTC, merged