Lesson 11 Task-7-14 - LEVEL2
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1315
Opened 2021-07-20 13:50 UTC by DeTELo

Не очень понимаю почему некоторые тесты проваливаются, вроде бы все выглядит красиво, но все-же хотел бы узнать как можно исправить данные ошибки и на что нужно смотреть, чтобы тесты не проваливались :3 Заранее спасибо 💯

2021-07-21 13:26 UTC, daniilsjb requested changes
Скорее всего это связано с тем, что вы переиспользуете одну и ту же репозиторию в разных тестах. Я также указал некоторые другие ошибки и упрощения на рассмотрение. Сорри, если получилось много, но на основе этих заданий строится практически весь остальной левел, так что нужен сильный фундамент 😎

2021-07-21 13:26 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/InMemoryBookRepository.java
> +    }
При использовании `removeIf` эти два методы становятся совсем тривиальными:

```java
@Override
public void deleteByAuthor(String bookAuthor) {
    books.removeIf(book -> book.getAuthor().equals(bookAuthor));
}

@Override
public void deleteByTitle(String bookTitle) {
    books.removeIf(book -> book.getTitle().equals(bookTitle));
}
```

2021-07-21 13:26 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/BookRepositoryTest.java
> +    InMemoryBookRepository inMemoryBookRepository = new InMemoryBookRepository();
Репозиторию не стоит шарить между тестами, поскольку у неё есть состояние. Каждому тесту нужно создавать свою, чистую репозиторию.

2021-07-21 13:26 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/BookRepositoryTest.java
> +        assertResultTest(inMemoryBookRepository.delete((long) 1), true, "Книга найдена и удалена (ID)!");
В числах типа `long` можно ставить суффикс `L` на конце, и тогда не нужно лишних преобразований.

2021-07-25 19:43 UTC, DeTELo commented
Алилуя :D Все тесты прошли! :3 Надеюсь все будет правильно 🥉

2021-07-26 12:09 UTC, daniilsjb requested changes
Осталась только одна серьёзная ошибка (всё остальное - заметки на будущее): в методе `save` нужно возвращать идентификатор сохранённой книги.

2021-07-26 12:09 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/InMemoryBookRepository.java
> +    }
На всякий случай уточню, почему я рекомендую в конечном счёте убрать этот геттер: поскольку возвращается ссылка на список, то через результат этого метода в него можно добавить элементы и тем самым изменить содержимое репозитория.

```java
public static void main(String[] args) {
    var repository = new InMemoryBookRepository();
    repository.save(new Book("A1", "B1"));
    repository.save(new Book("A2", "B2"));
    System.out.println(repository.count()); // output: 2
    
    var books = repository.getBooks();
    books.add(new Book("Big", "Problem"));
    System.out.println(repository.count()); // output: 3

    // Теперь в репозитории хранится новая книга, но поскольку она была
    // передана не через save, то у неё нет идентификатора. Очень плохо!
}
```
При тестировании можно использовать другие операции репозитории. В крайнем случае этот метод мог бы создавать копию списка.

2021-07-26 13:50 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/BookRepositoryTest.java
> +        list.add(new Book("JAVA3", "WORLD2"));
Я понял. На уроках такого не говорили :(

2021-07-26 13:55 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/Book.java
> +        }
Если я ставлю этот метод, но многие тесты проваливаются (

2021-07-26 13:55 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/InMemoryBookRepository.java
> +        return id;
Исправил )

2021-07-26 14:12 UTC, DeTELo commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/InMemoryBookRepository.java
> +    }
Тут я не очень понял. Почему нельзя оставить геттер?

2021-07-27 12:15 UTC, daniilsjb approved these changes
👍

2021-07-27 12:15 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_11/level_2/task_7_14/InMemoryBookRepository.java
> +    }
Как я уже объяснил выше, это даёт наружнему миру прямой доступ к содержимому репозитория. Весь смысл репозитория в том, что он скрывает логику хранения данных. Если код может получить ссылку на список `books`, то этот код же может этот список и изменить без ведома репозитория. Это в частности плохо, потому что идентификаторы назначает книгам именно метод `save` репозитории. Если напрямую добавить книгу, она останется без идентификатора.

Более того, геттер не всегда будет возможен для репозитории. Допустим, если бы данные хранились не в локальном списке, а где-то в удалённой базе данных, то поля `books` у вас бы не существовало, и геттер написать было бы невозможно. Поэтому его и нет в интерфейсе 🙂

В целях тестирования обычно стоит использовать другие методы репозитория. У вас уже есть операции вроде `count`, `findBy...` и прочее, ими можно пользоваться для проверки содержимого.

2021-07-27 12:16 UTC, merged