Lesson 14 - Level 2 - Task 17
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1488
Opened 2021-08-08 14:40 UTC by Ernests1992

2021-08-08 16:55 UTC, daniilsjb requested changes
Несколько ошибок форматирования. Также, стоит упростить тесты - их значительно больше, чем надо, и они слишком сильно разбиты. В реалии с такими тяжело работать и их читать, так что объединить их, а также можете убрать какие-то лишние. Главное только продемонстрировать работу каждого предиката, а также умение передавать предикат как абстрактный класс и лямбду.

2021-08-08 16:55 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/Apple.java
> +    public /*String*/ int getWeight() {
Лишние комментарии стоит убирать.

2021-08-08 16:55 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/ApplePredicate.java
> +}
Момент с форматированием: между именем метода и списком параметров пробел не ставится.

2021-08-08 16:55 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorage.java
> +    }
Код с потоками обычно очень длинный, поэтому каждое отдельное действие мы ставим на отдельную строчку. Например:

```java
public List<Apple> findApplesByColor(List<Apple> inventory, String color) {
    return inventory.stream()                    // создаём поток
        .filter(s -> s.getColor().equals(color)) // фильтруем поток
        .collect(Collectors.toList());           // создаём из потока список
}
```

2021-08-08 16:55 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorage.java
> +        }
Здесь нет пробелов после `for` и `if`.

2021-08-08 16:55 UTC, daniilsjb commented on src/test/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorageTest.java
> +class FruitStorageTest {
Тестов получается очень много, гораздо больше чем на самом деле нужно (GitHub даже не хочет изображать весь файл целиком в PR). В частности это связано с тем, что вы каждую отдельную проверку выделяете в свой тест. Так делать не нужно (хотя некоторые могут и заявлять, что так правильно). На каждый предикат достаточно одного простенького теста, покрывающего всю задачу:

```java
@Test
void shouldGetAllGreenApples() {
    var subject = new FruitStorage();
    var expected = List.of(
        new Apple("green", 200),
        new Apple("green", 90),
        new Apple("green", 50),
    );
    var actual = subject.findApplesByColor(subject.getAllApples(), "green");
    assertEquals(expected, actual);
}

...
```

2021-08-08 16:55 UTC, daniilsjb commented on src/test/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorageTest.java
> +}
Я вижу тесты с анонимными классами, но в [задании 17](https://github.com/konstantins-buts/jg-java-1-online-spring-april-tuesday-2021/blob/main/resources/lesson%2014/homework/level%202/Task_17.txt) упомянается тестирования при помощи лямбд. Столько примеров не обязательно, достаточно одного теста с анонимным классом и одного с лямбдой.

2021-08-08 18:40 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/Apple.java
> +    public /*String*/ int getWeight() {
Исправил.

2021-08-08 18:41 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/ApplePredicate.java
> +}
Исправил.

2021-08-08 18:42 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorage.java
> +    }
Исправил.

2021-08-08 18:43 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorage.java
> +        }
Исправил.

2021-08-08 18:50 UTC, Ernests1992 commented on src/test/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorageTest.java
> +class FruitStorageTest {
Исправил.

2021-08-08 18:52 UTC, Ernests1992 commented on src/test/java/students/ernests_subhankulovs/lesson_14/level_2/task_17/FruitStorageTest.java
> +}
Исправил.

2021-08-09 11:04 UTC, daniilsjb approved these changes
👍

2021-08-09 11:04 UTC, merged