Lesson 15 Task-5-8 - LEVEL2
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1513
Opened 2021-08-10 14:40 UTC by DeTELo

Lesson 15 Task-5-8 - LEVEL2

2021-08-11 14:29 UTC, daniilsjb requested changes
Курс может и закончился, но правильные отступы я пока не отменяю 🤓

2021-08-11 14:29 UTC, daniilsjb commented on src/test/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_5_8/QuadraticEqTest.java
> +    }
Немного не отформатировано 😅

2021-08-14 16:20 UTC, daniilsjb approved these changes
Отмена планов, всё норм 👌

2021-08-14 16:20 UTC, merged

2021-08-14 20:23 UTC, DeTELo commented
Ого, ничего себе :3 Просто никак времени небыло зайти проверить :)