Lesson 15 Task-9 - LEVEL2
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #1514
Opened 2021-08-10 15:05 UTC by DeTELo

Lesson 15 Task-9 - LEVEL2

2021-08-11 14:24 UTC, daniilsjb requested changes
Пока ещё не исправлен баг из самого задания, и есть ещё что улучшить 😁

2021-08-11 14:24 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_9/FraudDetector.java
> +        return true;
А при каком условии этот метод вернёт `false`? 🤔 Ведь не каждый трейдер является обманщиком.

2021-08-11 14:24 UTC, daniilsjb commented on src/test/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_9/FraudDetectorTest.java
> +        assertTrue(fraudDetector.isFraud(new Trader("Brok", "Sweden ")));
Собственно, почему здесь `true` а не `false`? 😁

2021-08-11 14:24 UTC, daniilsjb commented on src/test/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_9/FraudDetectorTest.java
> +    }
Небольшая придирка касаемо наименований. Тестам лучше всего давать имена, которые точно описывают, что они проверяют. Существуют разные конвенции (например, называеть тесты со слова `should`), но мы никакой конкретной не придерживаемся.

Тем не менее, тест `compareTraderName` проверяет оба условия - и забанненое имя, и забанненый город. Эти два сценария в принципе можно и разделить (считается хорошим, когда тест проверяет что-то одно). Тест `compareCity` вообще проверяет условие, где и имя, и город забаннены. А тест `isFraud` проверяет сценарий, в котором трейдер вообще-то молодец.

Если немного переосмыслить, то можно сделать как-то так:

```java
@Test
void isFraudWhenNameIsBanned() {
    assertTrue(fraudDetector.isFraud(new Trader("Pokemon", "Riga"));
}

@Test
void isFraudWhenCityIsBanned() {
    // в задании опечатка, город называется Sydney 🤓
    assertTrue(fraudDetector.isFraud(new Trader("Harold", "Sydney"));
}

@Test
void isFraudWhenNameAndCityAreBanned() {
    assertTrue(fraudDetector.isFraud(new Trader("Pokemon", "Sydney"));
}

@Test
void isNotFraud() {
    assertFalse(fraudDetector.isFraud(new Trader("Jeff", "Daugavpils"));
}
```

2021-08-11 14:24 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_9/FraudDetector.java
> +    }
К слову, эти методы должны быть приватными. Они являются деталями реализации `FraudDetector`. С точки зрения кода, который этим классом пользуется, важен только один вопрос: является ли трейдер обманщиком. Если бы наружний мир хотел рассматривать только какие-то конкретные критерии, то было бы лучше реализовать более гибкий подход через `enum`, но тут такого не требуется 🙂

2021-08-11 14:24 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_15/level_2/task_9/FraudDetector.java
> +        return compareTraderName(trader) || compareCity(trader);
И напоследок, мне не очень нравятся названия `compareTraderName` и `compareCity` (они намерено странноваты по заданию). Они что-то там проверяют, но что конкретно? Если `compareTraderName` воозвращает `true`, что это означает для метода `isFraud`?

Можно подумать над тем, есть ли более само-описыващие имена. Например, `isNameBanned` / `isCityBanned`, или `isFraudByName` / `isFraudByCity`.

2021-08-14 20:41 UTC, DeTELo commented
Вроде бы все исправил :3 Нужно ли ещё выполнять какие-то задания для получения аттестата? )

2021-08-14 21:18 UTC, daniilsjb approved these changes
У вас выполнены все левелы 1-2, так что теперь должно быть всё 😎👍

2021-08-14 21:18 UTC, merged