St vladimir aboltins lesson 2 level 1 task 2
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #166
Opened 2021-05-11 13:40 UTC by AzrailXD

У меня почему-то и первое задание приклеилось.

2021-05-11 19:59 UTC, daniilsjb requested changes
См. Task 1

2021-05-12 21:06 UTC, konstantins-buts commented
> У меня почему-то и первое задание приклеилось.

Напомню, что каждое задание нужно делать в отдельной ветке (branch), которую нужно создавать из ветки `main`. То есть, перед выполнением каждого задания, нужно переключиться на `origin/main` и создавать из него.

Это механизм работы git: вся история коммитов будет наследоваться от той ветки, из которой она была создана.

2021-05-17 17:56 UTC, AzrailXD commented
Посмотри, пожалуйста.

2021-05-17 18:34 UTC, daniilsjb approved these changes
👍

2021-05-17 19:11 UTC, merged