Lesson 3, Level 1, Task 1,2,3,4,5,6
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #176
Opened 2021-05-13 08:39 UTC by Linda-Ju

Возможно, класс Robot получился не очень красивым.. Но в RobotDemo кажется все работает.

2021-05-13 15:25 UTC, daniilsjb requested changes
Если у Вас есть вопросы по-поводу классов и объектов - задавайте. В изучении ООП главное первые шаги.

2021-05-13 15:25 UTC, daniilsjb commented on src/main/java/students/linda_junkina/lesson_3/level_1/task_1_2_3_4_5_6/Robot.java
> +        System.out.println("Hello Human!");
Классу `Robot` метод `main` не нужен. `main` - это точка входа всей программы. Для большинства простых проектов одной точки входа достаточно (хотя их может быть несколько, если в одном проекте есть несколько отдельных програм). В этом упражнении точка входа уже есть, это класс `RobotDemo`. Именно её нужно запускать.

2021-05-13 15:25 UTC, daniilsjb commented on src/main/java/students/linda_junkina/lesson_3/level_1/task_1_2_3_4_5_6/Robot.java
> +    String sayYourName;
В этом упражнении не требуется добавлять классу свойства. Свойства - это данные, которые ассоциируются с _каждым_ роботом (экземпляром). Класс только описывает _модель_, из которой могут строиться индивидуальные роботы. Здесь нужно только добавить классу методы (то есть комманды, которые каждый робот может выполнять).

2021-05-13 15:25 UTC, daniilsjb commented on src/main/java/students/linda_junkina/lesson_3/level_1/task_1_2_3_4_5_6/Robot.java
> +    public void sayYourNAme () {
Маленькая опечатка: имя стоит исправить на `sayYourName`, без заглавной буквы `A`.

2021-05-13 15:25 UTC, daniilsjb commented on src/main/java/students/linda_junkina/lesson_3/level_1/task_1_2_3_4_5_6/RobotDemo.java
> +        System.out.println(robot3.sayYourName);
Всё верно, кроме использования свойств. У класса `Robot` должны быть _методы_ `sayHello` и `sayYourName`. Метод - это комманда, которая говорит роботу, что он должен сделать (в данном случае, напечатать своё имя). Заметьте, как в Вашем решении повторяется один и тот же кусок логики:

```java
Robot robot = new Robot();
robot.sayHello = "Hello Human!";
System.out.println(robot.sayHello);
robot.sayYourName = "My name is ROBO!";
System.out.println(robot.sayYourName);
```
Вы создаёте сообщение на каждого робота, а затем напрямую его печатаете. Если научить самого робота печатать информацию о себе, то код станет гораздо проще:

```java
Robot robot = new Robot();
robot.sayHello();
robot.sayYourName();
```
Чтобы это работало, сама логика печатания имени должна быть описана в классе `Robot`, а не в классе `RobotDemo`. Сами методы очень простые - они просто вызывают `System.out.println` с соответствующими сообщениями (типа `Hello Human!`). Дальше остаётся только вызвать эти методы у каждого робота, как описано в `Task 6`:

```java
Robot robot1 = new Robot();
robot1.sayHello();
robot1.sayYourName();

Robot robot2 = new Robot();
robot2.sayHello();
robot2.sayYourName();
```

Также, не беспокойтись о том, что у всех роботов одинаковые имена. Эта проблема решается в одном из следующих упражнений, где наконец используются свойства, чтобы сделать каждого робота уникальным. 😃

2021-05-17 17:51 UTC, Linda-Ju commented
Я правильно понимаю, надо было написать как в примере CreditCard который я закоментировала?

2021-05-18 19:13 UTC, daniilsjb approved these changes
👍

2021-05-18 19:13 UTC, merged