Lesson 3 - Level 7 - Task 28
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #258
Opened 2021-05-17 13:45 UTC by Ernests1992

2021-05-17 18:59 UTC, daniilsjb requested changes

2021-05-17 18:59 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_3/level_7/task_28/Product.java
> +        return this.regularPrice - this.regularPrice * this.discount;
Небольшая ошибка: скидка выражается в процентах в промежутке 0-100, то есть если просто умножить скидку на цену, то результат будет неправильный. Сначала нужно её поделить на 100, чтобы нормализовать.

2021-05-18 08:00 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_3/level_7/task_28/Product.java
> +        return this.regularPrice - this.regularPrice * this.discount;
Исправил.

2021-05-18 19:14 UTC, daniilsjb approved these changes
👍

2021-05-18 19:14 UTC, merged