Finish - 3 lesson 5 level 17 task
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #270
Opened 2021-05-17 18:28 UTC by yareek22

2021-05-17 19:09 UTC, daniilsjb requested changes

2021-05-17 19:09 UTC, daniilsjb commented on src/main/java/students/eriks_jaloveckis/lesson_3/level_5/task_17/Dog.java
> +    }
Выводить имя три раза должна сама команда `voice`, а не `DogDemo`.

2021-05-17 19:09 UTC, daniilsjb commented on src/main/java/students/eriks_jaloveckis/lesson_3/level_5/task_17/Dog.java
> + String voice;
Свойство `voice` этому классу не нужно - это должен быть только метод.

2021-05-17 19:15 UTC, yareek22 commented on src/main/java/students/eriks_jaloveckis/lesson_3/level_5/task_17/Dog.java
> +    }
Я пытался найти в интернете, как сделать пробелы между name+name+name, но не нашел и в консоли все написано слитно

2021-05-17 19:15 UTC, yareek22 commented on src/main/java/students/eriks_jaloveckis/lesson_3/level_5/task_17/Dog.java
> + String voice;
Это я понял, забыл удалить

2021-05-17 19:17 UTC, daniilsjb commented on src/main/java/students/eriks_jaloveckis/lesson_3/level_5/task_17/Dog.java
> +    }
Можно просто сделать три отдельных вызова `System.out.println`, оно переводит курсор в консоли на новую строку. Альтернативно можно делать через конкатенацию строк и пробелы: `this.name + " " + this.name + " " + this.name`

2021-05-18 19:15 UTC, daniilsjb approved these changes
👍

2021-05-18 19:15 UTC, merged