Completed   Lesson 4 Level 4 Task 14
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #379
Opened 2021-05-22 22:29 UTC by arturwrls

2021-05-23 14:21 UTC, daniilsjb requested changes
Убедитесь, что названия тестов соответствуют сообщениям о провале теста.

2021-05-23 14:21 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_4/level_4/task_14/Calculator.java
> +        }
Во второй ветке можно упростить условие до `else if (secondNumber > thirdNumber)`.

А вообще у этого задания есть альтернативное, простое решение (хотя не совсем очевидное). Мы уже знаем, как найти наибольшее число из двух - метод `maxOfTwoNumbers`. Задача остаётся та же, только мы берём больше чисел. Вместо того, чтобы заново придумывать логику поиска наибольшего числа, мы можем просто привести проблему к той, которую уже решили. Если у нас есть числа `a, b, c`, то решение можно разделить на два шага: сначала найдём наибольшее число между `a, b`, а затем результат сравним с `c`.

В коде это выглядит гораздо проще, чем на словах:

```java
public int maxOfThreeNumbers(int a, int b, int c) {
    return maxOfTwoNumbers(maxOfTwoNumbers(a, b), c);
}
```

Этот код можно сделать ещё красивее, если воспользоваться техникой, которая называется "method overloading". На уроках это пока не затрагивалось, но если вкратце, то Java способна различать методы не только по имени, но и по параметрам. То есть `max(int a, int b)` и `max(int a, int b, int c)` - это два разных метода.

Тогда полностью решение может выглядеть так:

```java
public int max(int a, int b) {
    if (a > b) return a; else return b;
}

public int max(int a, int b, int c) {
    return max(max(a, b), c);
}
```

2021-05-23 14:21 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_4/level_4/task_14/CalculatorTest.java
> +        }
Я вижу, что у вас часто повторяется этот кусок логики: проверка результата, вывод "OK/FAIL", имя теста, и т.д. Предлагаю ввести метод `assertThatEqual` как у Константина в материалах к уроку. Этому методу можно передавать `actualResult` и `expectedResult` как параметры, а также имя или описание теста. Тогда вся эта проверка будет происходить внутри этого метода, и каждый тест может выглядеть примерно так:

```java
int firstNumber = 8;
int secondNumber = 5;
int expectedResult = firstNumber;

Calculator subject = new Calculator();
int actualResult = subject.maxOfTwoNumbers(firstNumber, secondNumber);

assertThatEqual(actualResult, expectedResult, "maxOfTwoNumbersTest_Option_1");
```

2021-05-23 14:21 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_4/level_4/task_14/CalculatorTest.java
> +            System.out.println("Expected result: " + expectedResult + ", Real result: " + realResult + ", maxOfThreeNumbersTest_Option_3 test = FAIL");
Ещё одна причина создать дополнительный метод: у вас есть несоответствия в названиях тестов и сообщениях. Например, этот тест называется `maxOfTwoNumbersTest_Option_2`, а при провале он выводится как `maxOfThreeNumbersTest_Option_3`.

В профессиональном мире очень часто возникают ошибки copy-paste кода, когда программисту нужно написать несколько похожих кусков кода, потому он их копирует, но при этом забывает поменять какую-то деталь (из личного опыта скажу, что в тестах такое возникает особенно часто). Обычно это является признаком того, что стоит добавить вспомогательный метод.

2021-05-24 00:32 UTC, arturwrls commented
Попробовал тут использовать method overloading в классе Calculator, как вы советовали, очень занятная штука оказывается, спасибо за совет, ну и немного подправил код, должно быть всё красиво😊

Ещё момент, в классе CalculatorTest для тестовых методов сделал один метод, в который собрал необходимы поля/переменные чтоб не повторять код, но у меня не все методы подходят под этот шаблон, где есть не просто "if ((realResult == expectedResult)",
а допустим еще дополнительные, как в методе - void threeNumbers_Option_4():
"if (realResult == expectedResult && expectedResult == secondNumber && thirdNumber != secondNumber)"
Не делать же под каждый следующий нестандартный метод, новый метод-шаблон.
Я конечно вышел из положения, но возможно есть какой-либо другой способ?
Спасибо

2021-05-24 09:25 UTC, daniilsjb commented
Выход есть, и он в чём-то похож на решение с `max`. Как правило методы вообще должны быть максимально просты, потому что тогда их проще переиспользовать, поэтому сведения к специфичным шаблонам стоит избегать. Зато когда методы нейтральны и просты, их можно объединять между собой для решения более сложных задач/сценариев.

Например, возьмём тест `threeNumbers_Option_5`. Там есть две проверки: `realResult == expectedResult && expectedResult == firstNumber`. Нам нужно, чтобы оба сравнения удались. Метод `checkCorrectOutput` может совершить одну проверку, значит, можно просто вызвать его дважды:

```java
checkCorrectOutput(expectedResult, realResult, "threeNumbers_Option_5");
checkCorrectOutput(expectedResult, firstNumber, "threeNumbers_Option_5");
```

При каждом вызове можно даже пометить внутри параметра `description`, какое конкретно условие мы проверяем. Здесь уже зависит от того, насколько далеко вы хотите идти с сообщениями о провалах.

В сценарии `threeNumbers_Option_4` принцип абсолютно тот же, но там мы сталкиваемся с оператором `!=`. Тут достаточно будет ввести ещё один вспомогательный метод, такой же как `checkCorrectOutput`, только который убеждается, что результаты отличаются. Дам маленький совет насчёт названий: в тестовых библиотеках обычно принято называть проверку условия словом "assert". Тогда можно создать два метода с красивыми названиями - `assertThatEqual` и `assertThatNotEqual`. Сценарий может выглядеть примерно так:

```java
assertThatEqual(expectedResult, realResult, "threeNumbers_Option_4");
assertThatEqual(expectedResult, secondNumber, "threeNumbers_Option_4");
assertThatNotEqual(thirdNumber, secondNumber, "threeNumbers_Option_4");
```

В принципе последняя проверка здесь необязательна, поскольку сам тестовый сценарий уже подразумевает, что второе и третье числа должны быть различными. Но я думаю, что это хороший повод потренироваться создавать для себя методы. 😃

2021-05-24 09:37 UTC, daniilsjb commented
Ещё кое-что вдогонку. Чтобы не нужно было дублировать имя теста, может пока его тоже вывести в отдельную переменную где-нибудь в самом начале теста. Типа так:

```java
void testCase123() {
    String testName = "testCase123";
    ...
    assertThatEqual(a, b, testName);
    assertThatEqual(b, c, testName);
}
```

2021-05-24 18:35 UTC, daniilsjb approved these changes
😀👍

2021-05-24 18:35 UTC, merged