Lesson 4 - Level 7 - Task 20.
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #434
Opened 2021-05-23 19:25 UTC by Ernests1992

2021-05-24 16:28 UTC, daniilsjb requested changes

2021-05-24 16:28 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_4/level_7/task_20/LightColorDetectorTest.java
> +        lightColorDetectorTest.testGreen(505, lightColorDetector);
Передавать экземпляр в качестве параметра - способ рабочий, но он не сильно упрощает код. Есть более простое решение: вспомните, что `LightColorDetectorTest ` - это класс, а значит может иметь свойства, которые можно использовать из методов. Можно просто сделать `LightColorDetector ` класс свойством и напрямую обращаться к нему из тестов:

```java
class LightColorDetectorTest {

    LightColorDetector subject = new LightColorDetector();

    public static void main(String[] args) { ... }

    ...

    public void lightColorDetectorAssert(int waveLength, String expectedResult, String testName) {
        String realResult = subject.detect(waveLength);
        ...
    }
}
```

2021-05-24 16:28 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_4/level_7/task_20/LightColorDetectorTest.java
> +    }
Если убрать параметр `lightColorDetector` в соответствии с подходом выше, то остаётся только `waveLength`. Как правило, тесты не принимают параметров. Существует понятие о параметризированных тестах, но чтобы их реализовать в данных условиях нужно ещё несколько концептов, которые не затрагивались на уроках (циклы и коллекции в частности).

Поскольку каждый тест вызывается только один раз и, следовательно, имеет дело только с одной длинной волны, я рекомендую просто писать её напрямую в теле теста:

```java
public void testViolet() {
    lightColorDetectorAssert(405, "Violet", "LightColorDetector test - Violet");
}
```

Тогда каждый тест будет содержать только тот код, который для него действительно уникален.

2021-05-25 05:05 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_4/level_7/task_20/LightColorDetectorTest.java
> +    }
Исправлено.

2021-05-25 05:05 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_4/level_7/task_20/LightColorDetectorTest.java
> +        lightColorDetectorTest.testGreen(505, lightColorDetector);
Исправлено.

2021-05-25 09:16 UTC, daniilsjb approved these changes
👍

2021-05-25 09:16 UTC, merged