Completed   Lesson 5 Level 2 Task 15
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #665
Opened 2021-05-31 19:46 UTC by arturwrls

2021-05-31 21:20 UTC, daniilsjb requested changes

2021-05-31 21:20 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_5/level_2/task_15/ArrayIncrement.java
> +        }
Не совсем. Нужно именно увеличить значение каждой ячейки на два, чтобы сам массив изменился, и тогда уже заново вывести его содержимое. Красиво будет использовать оператор `+=` 😎

2021-06-01 05:20 UTC, arturwrls commented on src/main/java/students/arturs_arutjunovs/lesson_5/level_2/task_15/ArrayIncrement.java
> +        }
Понял, переделал чуток, так даже наверное проще, странно что сразу не догадался так сделать, или все же имелось ввиду именно прописать каждую отдельно number[0]+=+2, number[1]+=+2, number[2]+=+2🤔

2021-06-01 09:57 UTC, daniilsjb commented on src/main/java/students/arturs_arutjunovs/lesson_5/level_2/task_15/ArrayIncrement.java
> +        }
Всё правильно, цикл здесь как раз хорошо заходит. Главное, чтобы изменился сам массив. Перед двойкой, кстати, лишний унарный оператор `+`. Он совершенно ничего не делает и существует только для симметрии с оператором `-`, так что его можно убрать 😄

2021-06-01 09:57 UTC, daniilsjb approved these changes
👍

2021-06-01 09:57 UTC, merged