Lesson 5 - Level 2 - Task 12
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #843
Opened 2021-06-09 20:33 UTC by jleshkev

2021-06-10 15:35 UTC, daniilsjb requested changes

2021-06-10 15:35 UTC, daniilsjb commented on src/main/java/students/jevgenij_leshkevich/lesson_5/level_2/task_12/Task12.java
> +        }
Очень хитрая ошибка. Дело в том, что в цикле for each нет возможности присвоить значения ячейкам массива - их можно только читать. Переменная `number` - это **копия** текущего элемента массива, которую создаёт для вас компилятор, то есть выражение `number = random.nextInt(...)` на самом деле переписывает только локальную копию.

Если вы после запуска этого цикла совершите другой цикл вдоль массива и напечатаете каждое значение заново, то получите сплошные нули. Следовательно, массив не заполнен.

2021-06-15 20:09 UTC, jleshkev commented on src/main/java/students/jevgenij_leshkevich/lesson_5/level_2/task_12/Task12.java
> +        }
Я это понял на 15-м задании, когда надо было вывести увеличенный (+2) массив :)

2021-06-16 08:22 UTC, daniilsjb approved these changes
👍

2021-06-16 08:22 UTC, merged