Lesson 7 - Level 7 - Task 11
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #878
Opened 2021-06-14 21:41 UTC by Ernests1992

2021-06-15 14:57 UTC, daniilsjb requested changes

2021-06-15 14:57 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordService.java
> +        wordRepetitions = new int[words.length];
❗ Объявления и присвоения стоит объединить в одну операцию. В Java не принято разделять эти операции, поскольку это увеличивает риск использования данных, которые ещё не были инициализированы. В общем, это дурной стиль.

2021-06-15 14:57 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordService.java
> +        return text.split("[,.()\\-\\s*]+");
Проще использовать выражение `\\W+`, оно само покроет все знаки препинания и прочее 😉

2021-06-15 14:57 UTC, daniilsjb commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordServiceTest.java
> +    }
Касаемо тестов, можно ещё придумывать более странные случаи и убеждаться, что метод отрабатывает верно. Например:

- строка пустая
- в строке только одно слово
- каждое слово встречается одно и то же количество раз
- и т.д.

2021-06-15 15:24 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordService.java
> +        wordRepetitions = new int[words.length];
Исправил.

2021-06-15 19:24 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordService.java
> +        return text.split("[,.()\\-\\s*]+");
Заменил выражением "([^A-Za-zА-ЯЁа-яё])+".
Как выяснилосьб "\\W+" не реагирует на кириллицу.

2021-06-15 19:25 UTC, Ernests1992 commented on src/main/java/students/ernests_subhankulovs/lesson_7/level_7/task_11/WordServiceTest.java
> +    }
Дополнил.

2021-06-16 08:27 UTC, daniilsjb approved these changes
👍

Кстати, для работы с регулярными выражениями очень хорош [этот сайт](https://regexr.com/), возможно вы его уже встречали 🙂

2021-06-16 08:27 UTC, merged