St dmitrijs matrenicevs lesson 7 level 1 task 1
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #883
Opened 2021-06-15 16:32 UTC by DeTELo

St dmitrijs matrenicevs lesson 7 level 1 task 1

2021-06-15 16:33 UTC, DeTELo commented
Случайно добавил с другого бранча, и не очень понимаю как убрать (

2021-06-16 16:22 UTC, daniilsjb requested changes
Не доделано 🙃

2021-06-16 16:22 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordServiceTest.java
> +        wordServiceTest.testWordsResult();
Не знаю как у вас, но у меня эти тесты проваливаются 🤔

2021-06-16 16:22 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordService.java
> +        return text.split("A");
Это не разбивает строку на слова 🤔 Методу `split` нужно передать правильное регулярное выражение. Дам подсказку: `\\W+` должно работать нормально 😁

2021-06-16 16:22 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordService.java
> +            return sum;
Здесь затесался лишний `return`. При первой же итерации этот цикл завершится.

2021-06-16 16:22 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordService.java
> +        int sum = 0;
Эту переменную стоит назвать скорее `count`.

2021-06-16 16:22 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordService.java
> +    }
Мне не кажется, что частоту встречи слова стоит хранить в массиве строк. Всё-таки частота - это числа. Обычно наибольшее число мы ищем через оператор `>`, здесь вместо этого `equals` 🤔

2021-06-16 18:01 UTC, DeTELo commented
Вроде исправил, но не понимаю где ошибка может быть. В идее горит все зеленым, а на деле в 2 тестах FAIL, хммм ( Может можете подсказать где ошибка?

2021-06-16 19:07 UTC, daniilsjb requested changes
Иногда бывает такое, что неправильно составлен сам тест 😁

2021-06-16 19:07 UTC, daniilsjb commented on src/main/java/students/dmitrijs_matrenicevs/lesson_7/level_1/task_1/WordServiceTest.java
> +    }
Здесь точно запутаны тестовые данные, некоторые тесты почему-то ожидают несколько слов (хотя метод должен вернуть только одно), некоторые вообще ожидают слова, которых в тексте нет 🤔 В общем, нужно переосмыслить тестовые сценарии.

Предлагаю так:

```java
public void testWordsOne() {
    String text = "a a b a b b a b c c a c";
    String actual = wordService.findMostFrequentWord(text);
    String expected = "a";
    resultTestWords(actual.equals(expected), "Most frequent word (happy case)");
}

...
```

Стоит также проверить сценарии где:

- есть несколько слов, которые встречаются наиболее часто
- в тексте есть только одно слово
- в тексте нет слов вообще

2021-06-16 19:45 UTC, DeTELo commented
Вроде получилось 🥉

2021-06-17 08:39 UTC, daniilsjb approved these changes
👍

2021-06-17 08:39 UTC, merged