Добавила Lesson 4 Level 3 Tasks 7-9
konstantins-buts/jg-java-1-online-spring-april-tuesday-2021 pull request #939
Opened 2021-06-18 11:40 UTC by OK2021OT

2021-06-18 18:31 UTC, daniilsjb requested changes

2021-06-18 18:31 UTC, daniilsjb commented on src/main/java/students/olga_t/lesson_4/level_3/tasks_7_9/Task9.java
> +    }
Буквально маленькая неточность: числа ещё могут быть между собой равны, и здесь это не учитывается. Например, попробуйте ввести 4, 5, 5. Программа скажет, что число 4 самое большое.

Чтобы это исправить, достаточно везде заменить оператор `>` на `>=`, то есть просто убедиться, что другие числа не больше текущего (IDEA может даже подсказать дополнительные упрощения).

2021-06-19 10:11 UTC, OK2021OT commented
Исправила Lesson 4 Level 3 Task 9

2021-06-19 17:35 UTC, daniilsjb approved these changes
👍

2021-06-19 17:35 UTC, merged